// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO-ziORrLtFb5bgS_byXNzLyDB5VIeLLI',
    appId: '1:201953565667:web:4cee64be63f85e19a99ed6',
    messagingSenderId: '201953565667',
    projectId: 'labeeb-app-2026',
    authDomain: 'labeeb-app-2026.firebaseapp.com',
    storageBucket: 'labeeb-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXeH4hx2PUK-j_B2YDslA03_Mnk_ngXbw',
    appId: '1:201953565667:android:4ca9c7f72a468fb6a99ed6',
    messagingSenderId: '201953565667',
    projectId: 'labeeb-app-2026',
    storageBucket: 'labeeb-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlfNEAkaq1pE7Y_vQ40nuM83b1plauEx4',
    appId: '1:201953565667:ios:ac8daa9855980b9da99ed6',
    messagingSenderId: '201953565667',
    projectId: 'labeeb-app-2026',
    storageBucket: 'labeeb-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.labeebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlfNEAkaq1pE7Y_vQ40nuM83b1plauEx4',
    appId: '1:201953565667:ios:ac8daa9855980b9da99ed6',
    messagingSenderId: '201953565667',
    projectId: 'labeeb-app-2026',
    storageBucket: 'labeeb-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.labeebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO-ziORrLtFb5bgS_byXNzLyDB5VIeLLI',
    appId: '1:201953565667:web:814cc9102e87b1e1a99ed6',
    messagingSenderId: '201953565667',
    projectId: 'labeeb-app-2026',
    authDomain: 'labeeb-app-2026.firebaseapp.com',
    storageBucket: 'labeeb-app-2026.firebasestorage.app',
  );
}
